// nextjs-ui/app/components/warren/app-dialog.tsx
'use client'

import { Dialog, DialogPanel, DialogTitle, Transition, TransitionChild } from '@headlessui/react'
import { Fragment, type ReactNode } from 'react'

export function AppDialog({
  open,
  onClose,
  title,
  maxWidthClass = 'max-w-md',
  children,
}: {
  open: boolean
  onClose: () => void
  title?: string
  maxWidthClass?: string
  children: ReactNode
}) {
  return (
    <Transition show={open} as={Fragment} appear>
      <Dialog as="div" className="relative z-50" onClose={onClose}>
        <TransitionChild
          as={Fragment}
          enter="duration-200 ease-out"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="duration-150 ease-in"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-black/40 dark:bg-black/70 backdrop-blur-sm" />
        </TransitionChild>

        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4 sm:p-6">
            <TransitionChild
              as={Fragment}
              enter="duration-200 ease-out"
              enterFrom="opacity-0 translate-y-2 sm:scale-95"
              enterTo="opacity-100 translate-y-0 sm:scale-100"
              leave="duration-150 ease-in"
              leaveFrom="opacity-100 translate-y-0 sm:scale-100"
              leaveTo="opacity-0 translate-y-2 sm:scale-95"
            >
              <DialogPanel
                className={[
                  'relative w-full bg-modal text-text rounded-2xl shadow-2xl ring-1 ring-default/70 dark:ring-white/10',
                  'flex flex-col max-h-[88vh]',
                  maxWidthClass,
                ].join(' ')}
              >
                {title && (
                  <DialogTitle className="px-6 pt-5 pb-4 text-base font-semibold text-text border-b border-default">
                    {title}
                  </DialogTitle>
                )}
                {children}
              </DialogPanel>
            </TransitionChild>
          </div>
        </div>
      </Dialog>
    </Transition>
  )
}

// ui/app/components/AppDialog.vue
<script setup lang="ts">
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  TransitionChild,
  TransitionRoot,
} from '@headlessui/vue'

withDefaults(defineProps<{
  open: boolean
  title?: string
  // Tailwind max-w-* class. Override per modal that needs more width.
  maxWidthClass?: string
}>(), {
  title: undefined,
  maxWidthClass: 'max-w-md',
})

const emit = defineEmits<{
  (e: 'close'): void
}>()
</script>

<template>
  <TransitionRoot :show="open" as="template" appear>
    <Dialog as="div" class="relative z-50" @close="emit('close')">
      <TransitionChild
        as="template"
        enter="duration-200 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-150 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-black/40 dark:bg-black/70 backdrop-blur-sm" />
      </TransitionChild>

      <div class="fixed inset-0 overflow-y-auto">
        <div class="flex min-h-full items-center justify-center p-4 sm:p-6">
          <TransitionChild
            as="template"
            enter="duration-200 ease-out"
            enter-from="opacity-0 translate-y-2 sm:scale-95"
            enter-to="opacity-100 translate-y-0 sm:scale-100"
            leave="duration-150 ease-in"
            leave-from="opacity-100 translate-y-0 sm:scale-100"
            leave-to="opacity-0 translate-y-2 sm:scale-95"
          >
            <DialogPanel
              :class="[
                'relative w-full bg-modal text-text rounded-2xl shadow-2xl ring-1 ring-default/70 dark:ring-white/10',
                'flex flex-col max-h-[88vh]',
                maxWidthClass,
              ]"
            >
              <DialogTitle
                v-if="title"
                class="px-6 pt-5 pb-4 text-base font-semibold text-text border-b border-default"
              >
                {{ title }}
              </DialogTitle>
              <slot />
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>
