// nextjs-ui/app/components/warren/motion-tile.tsx
'use client'

import { useState } from 'react'
import { PencilSquareIcon, XMarkIcon } from '@heroicons/react/20/solid'
import type { SensorView } from '@/lib/shared/types'
import { ConfirmDialog } from './confirm-dialog'

export function MotionTile({
  sensor,
  editing,
  isOffline,
  recentMotion,
  motionLabel,
  onViewHistory,
  onEditSensor,
  onRemoveSensor,
}: {
  sensor: SensorView
  editing: boolean
  isOffline: boolean
  recentMotion: boolean
  motionLabel: string | null
  onViewHistory: (sensor: SensorView) => void
  onEditSensor: (sensorId: number) => void
  onRemoveSensor: (sensorId: number) => void
}) {
  const [confirmRemove, setConfirmRemove] = useState(false)
  const valueText = !sensor.lastMotion ? '—' : recentMotion ? 'Detected' : 'Clear'

  return (
    <button
      type="button"
      onClick={() => onViewHistory(sensor)}
      className={[
        'group/tile relative flex flex-col items-start gap-1.5 rounded-2xl px-4 py-4 text-left ring-1 transition cursor-pointer',
        isOffline
          ? 'bg-error/[0.04] ring-error/30'
          : recentMotion
            ? 'bg-accent/10 ring-accent/30'
            : 'bg-surface-2/60 ring-default/70 hover:bg-surface-2 hover:ring-default dark:ring-white/5 dark:hover:ring-white/10',
      ].join(' ')}
    >
      <div className="flex items-center justify-between w-full">
        <span className="text-lg">🏃</span>
        {isOffline ? (
          <span className="badge badge-error">Offline</span>
        ) : recentMotion ? (
          <span className="badge badge-warning animate-warren-pulse">Live</span>
        ) : null}
      </div>
      <div className={`text-2xl font-bold leading-none mt-1 ${isOffline ? 'text-subtle' : recentMotion ? 'text-warning' : 'text-text'}`}>
        {valueText}
      </div>
      <div className="text-xs text-subtle uppercase tracking-wider font-medium">Motion</div>
      {sensor.label && <div className="text-xs text-muted truncate max-w-full">{sensor.label}</div>}
      {sensor.lastMotion && motionLabel && <div className="text-xs text-subtle">{motionLabel}</div>}

      {editing && (
        <div className="absolute top-1.5 right-1.5 flex items-center gap-0.5 rounded-xl bg-surface/75 p-0.5 backdrop-blur-md transition-opacity pointer-fine:opacity-0 pointer-fine:group-hover/tile:opacity-100 dark:bg-surface/65">
          <span
            role="button"
            tabIndex={0}
            className="btn-icon size-7"
            title="Edit"
            onClick={(e) => { e.stopPropagation(); onEditSensor(sensor.id) }}
          >
            <PencilSquareIcon className="size-3.5" />
          </span>
          <span
            role="button"
            tabIndex={0}
            className="btn-icon size-7 hover:!text-error hover:!ring-error/40"
            title="Remove"
            onClick={(e) => { e.stopPropagation(); setConfirmRemove(true) }}
          >
            <XMarkIcon className="size-3.5" />
          </span>
        </div>
      )}

      <ConfirmDialog
        open={confirmRemove}
        message="Remove this sensor from the room?"
        confirmLabel="Remove"
        onConfirm={() => { onRemoveSensor(sensor.id); setConfirmRemove(false) }}
        onCancel={() => setConfirmRemove(false)}
      />
    </button>
  )
}

// ui/app/components/MotionTile.vue
<script setup lang="ts">
import { PencilSquareIcon, XMarkIcon } from '@heroicons/vue/20/solid'
import type { SensorView } from '../../shared/types'

const props = defineProps<{
  sensor: SensorView
  editing: boolean
  isOffline: boolean
  recentMotion: boolean
  motionLabel: string | null
}>()

const emit = defineEmits<{
  (e: 'view-history', sensor: SensorView): void
  (e: 'edit-sensor', sensorId: number): void
  (e: 'remove-sensor', sensorId: number): void
}>()

const confirmRemove = ref(false)

const valueText = computed(() => {
  if (!props.sensor.lastMotion) return '—'
  return props.recentMotion ? 'Detected' : 'Clear'
})
</script>

<template>
  <button
    :class="[
      'group/tile relative flex flex-col items-start gap-1.5 rounded-2xl px-4 py-4 text-left ring-1 transition cursor-pointer',
      isOffline
        ? 'bg-error/[0.04] ring-error/30'
        : recentMotion
          ? 'bg-accent/10 ring-accent/30'
          : 'bg-surface-2/60 ring-default/70 hover:bg-surface-2 hover:ring-default dark:ring-white/5 dark:hover:ring-white/10',
    ]"
    @click="emit('view-history', sensor)"
  >
    <div class="flex items-center justify-between w-full">
      <span class="text-lg">🏃</span>
      <span v-if="isOffline" class="badge badge-error">Offline</span>
      <span v-else-if="recentMotion" class="badge badge-warning animate-warren-pulse">Live</span>
    </div>
    <div :class="['text-2xl font-bold leading-none mt-1', isOffline ? 'text-subtle' : recentMotion ? 'text-warning' : 'text-text']">
      {{ valueText }}
    </div>
    <div class="text-xs text-subtle uppercase tracking-wider font-medium">Motion</div>
    <div v-if="sensor.label" class="text-xs text-muted truncate max-w-full">{{ sensor.label }}</div>
    <div v-if="sensor.lastMotion && motionLabel" class="text-xs text-subtle">{{ motionLabel }}</div>

    <div v-if="editing" class="absolute top-1.5 right-1.5 flex items-center gap-0.5 rounded-xl bg-surface/75 p-0.5 backdrop-blur-md transition-opacity pointer-fine:opacity-0 pointer-fine:group-hover/tile:opacity-100 dark:bg-surface/65">
      <span class="btn-icon size-7" title="Edit" @click.stop="emit('edit-sensor', sensor.id)">
        <PencilSquareIcon class="size-3.5" />
      </span>
      <span class="btn-icon size-7 hover:!text-error hover:!ring-error/40" title="Remove" @click.stop="confirmRemove = true">
        <XMarkIcon class="size-3.5" />
      </span>
    </div>

    <ConfirmDialog
      v-if="confirmRemove"
      message="Remove this sensor from the room?"
      confirm-label="Remove"
      @confirm="emit('remove-sensor', sensor.id); confirmRemove = false"
      @cancel="confirmRemove = false"
    />
  </button>
</template>
