// nextjs-ui/app/components/warren/theme-toggle.tsx
'use client'

import { MoonIcon, SunIcon } from '@heroicons/react/20/solid'
import { useTheme } from '@/lib/hooks/use-theme'

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme()
  const Icon = theme === 'dark' ? MoonIcon : SunIcon
  return (
    <button
      type="button"
      onClick={toggleTheme}
      className="btn-icon"
      aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
    >
      <Icon className="size-5" />
    </button>
  )
}

// ui/app/components/ThemeToggle.vue
<script setup lang="ts">
import { SunIcon, MoonIcon } from '@heroicons/vue/24/outline'

const { theme, toggleTheme } = useTheme()
</script>

<template>
  <button
    type="button"
    class="btn-icon"
    :title="theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'"
    :aria-label="theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'"
    @click="toggleTheme"
  >
    <SunIcon v-if="theme === 'dark'" class="size-4" />
    <MoonIcon v-else class="size-4" />
  </button>
</template>
